export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";
export const MAYBE_LOAD_SUGGESTIONS = "MAYBE_LOAD_SUGGESTIONS";
export const LOAD_SUGGESTIONS = "LOAD_SUGGESTIONS";
export const SET_MATCHING_VALUES_TO_SUGGESTIONS = "SET_MATCHING_VALUES_TO_SUGGESTIONS";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";
